// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Database;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(BancoDeDados))]
    partial class BancoDeDadosModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.21");

            modelBuilder.Entity("backend.Models.Livro", b =>
                {
                    b.Property<int>("LivroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataLancamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadePaginas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecomendacaoNegativa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecomendacaoPositiva")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sinopse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LivroId");

                    b.ToTable("Livros");

                    b.HasData(
                        new
                        {
                            LivroId = 1,
                            Autor = "George Orwell",
                            Categoria = "Ficção",
                            DataCadastro = new DateTime(2024, 1, 18, 18, 38, 17, 989, DateTimeKind.Local).AddTicks(9610),
                            DataLancamento = "08/06/1949",
                            Editora = "Editora Secker and Warburg",
                            Genero = "Distopia",
                            QuantidadePaginas = 135,
                            RecomendacaoNegativa = 13,
                            RecomendacaoPositiva = 43,
                            Sinopse = "Distopia sobre um regime totalitário de vigilância.",
                            Titulo = "1984"
                        },
                        new
                        {
                            LivroId = 2,
                            Autor = "J.R.R. Tolkien",
                            Categoria = "Fantasia",
                            DataCadastro = new DateTime(2024, 1, 18, 18, 38, 17, 989, DateTimeKind.Local).AddTicks(9634),
                            DataLancamento = "29/07/1954",
                            Editora = "Allen & Unwin",
                            Genero = "Alta Fantasia",
                            QuantidadePaginas = 92,
                            RecomendacaoNegativa = 49,
                            RecomendacaoPositiva = 17,
                            Sinopse = "Épico de fantasia sobre a luta contra o mal em uma terra mítica.",
                            Titulo = "O Senhor dos Anéis"
                        },
                        new
                        {
                            LivroId = 3,
                            Autor = "Antoine de Saint-Exupéry",
                            Categoria = "Infantil",
                            DataCadastro = new DateTime(2024, 1, 18, 18, 38, 17, 989, DateTimeKind.Local).AddTicks(9639),
                            DataLancamento = "06/04/1943",
                            Editora = "Reynal & Hitchcock",
                            Genero = "Fábula",
                            QuantidadePaginas = 321,
                            RecomendacaoNegativa = 15,
                            RecomendacaoPositiva = 26,
                            Sinopse = "Uma fábula sobre amor e perda, vista através dos olhos de um príncipe viajante.",
                            Titulo = "O Pequeno Príncipe"
                        },
                        new
                        {
                            LivroId = 4,
                            Autor = "John Green",
                            Categoria = "Romance",
                            DataCadastro = new DateTime(2024, 1, 18, 18, 38, 17, 989, DateTimeKind.Local).AddTicks(9643),
                            DataLancamento = "10/01/2012",
                            Editora = "Dutton Books",
                            Genero = "Drama",
                            QuantidadePaginas = 309,
                            RecomendacaoNegativa = 38,
                            RecomendacaoPositiva = 41,
                            Sinopse = "Uma emocionante história de amor e tragédia de dois adolescentes com câncer.",
                            Titulo = "A Culpa é das Estrelas"
                        },
                        new
                        {
                            LivroId = 5,
                            Autor = "Miguel de Cervantes",
                            Categoria = "Romance",
                            DataCadastro = new DateTime(2024, 1, 18, 18, 38, 17, 989, DateTimeKind.Local).AddTicks(9647),
                            DataLancamento = "16/01/1605",
                            Editora = "Francisco de Robles",
                            Genero = "Paródia",
                            QuantidadePaginas = 68,
                            RecomendacaoNegativa = 20,
                            RecomendacaoPositiva = 19,
                            Sinopse = "As aventuras de um nobre espanhol obcecado por histórias de cavalaria.",
                            Titulo = "Dom Quixote"
                        },
                        new
                        {
                            LivroId = 6,
                            Autor = "George Orwell",
                            Categoria = "Ficção",
                            DataCadastro = new DateTime(2024, 1, 18, 18, 38, 17, 989, DateTimeKind.Local).AddTicks(9651),
                            DataLancamento = "17/08/1945",
                            Editora = "Secker and Warburg",
                            Genero = "Sátira",
                            QuantidadePaginas = 148,
                            RecomendacaoNegativa = 27,
                            RecomendacaoPositiva = 40,
                            Sinopse = "Uma sátira política sobre animais que buscam liberdade em uma fazenda.",
                            Titulo = "A Revolução dos Bichos"
                        },
                        new
                        {
                            LivroId = 7,
                            Autor = "Markus Zusak",
                            Categoria = "Histórico",
                            DataCadastro = new DateTime(2024, 1, 18, 18, 38, 17, 989, DateTimeKind.Local).AddTicks(9654),
                            DataLancamento = "23/09/2005",
                            Editora = "Intrínseca",
                            Genero = "Drama",
                            QuantidadePaginas = 351,
                            RecomendacaoNegativa = 10,
                            RecomendacaoPositiva = 39,
                            Sinopse = "Uma história emocionante ambientada na Alemanha nazista, narrada pela Morte.",
                            Titulo = "A Menina que Roubava Livros"
                        },
                        new
                        {
                            LivroId = 8,
                            Autor = "Ray Bradbury",
                            Categoria = "Ficção",
                            DataCadastro = new DateTime(2024, 1, 18, 18, 38, 17, 989, DateTimeKind.Local).AddTicks(9658),
                            DataLancamento = "19/10/1953",
                            Editora = "Ballantine Books",
                            Genero = "Distopia",
                            QuantidadePaginas = 213,
                            RecomendacaoNegativa = 21,
                            RecomendacaoPositiva = 22,
                            Sinopse = "Em um futuro distópico, os livros são proibidos e os 'bombeiros' queimam qualquer um que encontram.",
                            Titulo = "Fahrenheit 451"
                        },
                        new
                        {
                            LivroId = 9,
                            Autor = "Harper Lee",
                            Categoria = "Ficção",
                            DataCadastro = new DateTime(2024, 1, 18, 18, 38, 17, 989, DateTimeKind.Local).AddTicks(9661),
                            DataLancamento = "11/07/1960",
                            Editora = "J. B. Lippincott & Co.",
                            Genero = "Drama",
                            QuantidadePaginas = 134,
                            RecomendacaoNegativa = 13,
                            RecomendacaoPositiva = 50,
                            Sinopse = "Um clássico da literatura americana que aborda questões de justiça e preconceito racial.",
                            Titulo = "O Sol é Para Todos"
                        },
                        new
                        {
                            LivroId = 10,
                            Autor = "Lewis Carroll",
                            Categoria = "Fantasia",
                            DataCadastro = new DateTime(2024, 1, 18, 18, 38, 17, 989, DateTimeKind.Local).AddTicks(9665),
                            DataLancamento = "26/11/1865",
                            Editora = "Macmillan",
                            Genero = "Literatura Infantil",
                            QuantidadePaginas = 343,
                            RecomendacaoNegativa = 32,
                            RecomendacaoPositiva = 18,
                            Sinopse = "A clássica história de uma menina que cai em um buraco de coelho e entra em um mundo de fantasia.",
                            Titulo = "Alice no País das Maravilhas"
                        });
                });

            modelBuilder.Entity("backend.Models.LivroFavoritado", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LivroId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UsuarioId", "LivroId");

                    b.HasIndex("LivroId");

                    b.ToTable("LivrosFavoritados");
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Senha = "1234",
                            Username = "dev"
                        });
                });

            modelBuilder.Entity("backend.Models.LivroFavoritado", b =>
                {
                    b.HasOne("backend.Models.Livro", "Livro")
                        .WithMany("LivrosFavoritados")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", "Usuario")
                        .WithMany("LivrosFavoritados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.Models.Livro", b =>
                {
                    b.Navigation("LivrosFavoritados");
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.Navigation("LivrosFavoritados");
                });
#pragma warning restore 612, 618
        }
    }
}
